import type { AvailableComponent } from '@/lib/types';
import {
  CaseSensitive,
  CheckSquare,
  ChevronDown,
  CircleDot,
  Hash,
  KeyRound,
  Mail,
  MessageSquare,
  CalendarDays,
  ToggleRight,
  Phone,
  Link,
  Search,
  File,
  Image,
  Text,
  Table,
} from 'lucide-react';

export const AVAILABLE_COMPONENTS: AvailableComponent[] = [
  { name: 'Text Input', icon: CaseSensitive, type: 'text' },
  { name: 'Email', icon: Mail, type: 'email' },
  { name: 'Password', icon: KeyRound, type: 'password' },
  { name: 'Number', icon: Hash, type: 'number' },
  { name: 'Text Area', icon: MessageSquare, type: 'textarea' },
  { name: 'Dropdown', icon: ChevronDown, type: 'dropdown' },
  { name: 'Checkbox', icon: CheckSquare, type: 'checkbox' },
  { name: 'Date', icon: CalendarDays, type: 'date' },
  { name: 'Radio Group', icon: CircleDot, type: 'radiogroup' },
  { name: 'Switch', icon: ToggleRight, type: 'switch' },
  { name: 'Phone', icon: Phone, type: 'tel' },
  { name: 'URL', icon: Link, type: 'url' },
  { name: 'Search', icon: Search, type: 'search' },
  { name: 'File', icon: File, type: 'file' },
  { name: 'Image', icon: Image, type: 'image' },
  { name: 'Rich Text', icon: Text, type: 'richtext' },
  { name: 'Data Table', icon: Table, type: 'datatable' },
];
